require "lquenti.options"
require "lquenti.keymaps"
require "lquenti.plugins"
require "lquenti.colorscheme"
require "lquenti.cmp"
require "lquenti.lsp"
require "lquenti.telescope"
require "lquenti.treesitter"
